environment: test

# corp related
access_control_allow_origin: http://localhost:3000

# https related
port: 5600
enable_https: false
# https_certfile_path: "certs/localhost.crt"
# https_keyfile_path: "certs/localhost.key"

# session cookie related
session_cookie_name: "_chat_session"
session_cookie_expires_days: 30
session_cookie_path: "/"
session_cookie_domain: "localhost"
# session_cookie_secure: false

# model name related
model_mapping:
  gpt-3.5: "gpt-3.5-turbo-0125"
  gpt-4: "gpt-4-0125-preview"
  llama2: "llama2-7b"

# external api related 
openai_api_key: "12345678901234567890123456789012"

llama_base_url: "http://localhost:5000/v1"
llama_api_key: "12345678901234567890123456789012"

# encrypt/decrypt related
encrypt_key: "12345678901234567890123456789012"
encrypt_salt: "1234123412341234" # must be 16 bytes

# database file related
app_data_db_name: "/var/data/app-data.db"
key_db_name: "/var/data/key-data.db"

# log file related
log_file_path: "/var/log/prompt_tool/backend-app.log"

# user budget
default_monthly_budget: 5
