tools:
  - class_name: "retool.CustomSandboxFusionTool"
    config:
      sandbox_fusion_url: "https://sandboxfusion.yellowday.day/run_code"
      num_workers: 8
      enable_global_rate_limit: true
      rate_limit: 8
      default_timeout: 30
      default_language: "python"
      memory_limit_mb: 1024
      type: native

    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "A tool for executing code."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The code to execute."
          required: ["code"]